title: Smart Irrigation System
email: hxa04@mail.aub.edu

baseurl: "/SmartIrrigationSystem" # the subpath of your site, e.g. /blog
linkedin_username: hsandid
github_username:  hsandid

# Build settings
theme: minima
  
markdown: kramdown
