title: Documentation
highlighter: rouge
url: "https://hsandid.github.io"  
baseurl: "/SmartIrrigationSystem"
permalink: pretty
# exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
repository: "hsandid/SmartIrrigationSystem"
markdown: GFM
heading_anchors: false

# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
search_enabled: false
back_to_top: true
back_to_top_text: "Back to top"

