title: Smart Irrigation System
email : "hxa04@mail.aub.edu"
highlighter: rouge
  
baseurl: "/SmartIrrigationSystem" # the subpath of your site, e.g. /blog


# Build settings
theme: minima
  
markdown: GFM

minima:
    github: hsandid
    linkedin: hsandid
